/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package environmental.stewardship.assignment;

/**
 *
 * @author SyphiN
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        resetQuiz();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void resetQuiz(){
        Question q1 = new Question("What which of the following is a technology that has positively and directly impacted human health?", "Nuclear Energy", "Insulin Pumps", "Transport Technology", "Temperature Control", "B");
        Question q2 = new Question("Which of the following is a E-Waste recycling Initiative?", "McDonalds", "TD", "EPRA", "CNA", "C");
        Question q3 = new Question("Which of the following is a valid reason for why E-Waste is Bad?", "Waste of materials leading to, more metal mining destroying habitats", "E-Waste tastes bad", "Foreign countries get too much free technology", "Because I have to resist the urge to throw it out", "A");
        Question q4 = new Question("What is the CNA?", "Could Not Answer", "Continental North-Atlantic", "Corporate Nutrition Association", "Canadian Nuclear Association", "D");
        Question q5 = new Question("What is the most efficient Energy Source?", "Fossil Fuels", "Hydro-Electric", "Solar Energy", "Nuclear Energy", "D");
        Question q6 = new Question("Which of the following is a negative health effect of personal computers?", "Diabetes", "Poor Posture", "Racism", "Osteoperosis", "B");
        Question q7 = new Question("Not including nuclear energy, what else does the CNA do?", "Diagnose Illnesses", "Give people Cancer", "Rare mineral mining", "Build Weapons of Mass Destruction", "A");
        Question q8 = new Question("How do cell phones affect your sleep?", "5G waves from the phones disrupt your melatonin", "Gotta keep up the grind", "Blue light disrupts your circadian rythms", "Youtube is just too interesting to turn off", "C");
        Question q9 = new Question("Which technology was used to Make Covid Vaccines?", "Microchips", "Arsenic", "Covid Killer Nanobots", "MRNA printers", "D");
        Question q10 = new Question("How should you get rid of old Electronics?", "Throw it in the trash", "At a designated E-Waste recycling place", "Recycle in the Blue Bin", "Recycle in the Black Bin", "B");
        Question q11 = new Question("How has IT changed the world?", "Revolutionalized communications allowing for instant communication over long distances", "Created Twitter, allowing for me to STAN Loona", "Allows the CCP to track my information using TikTok", "It didn't", "A");
        Question q12 = new Question("What is Environmental Stewardship?", "The little mouse from Stewart Little", "Actively being aware of and participating in ensuring the health and Safety of the Earth and People", "One of the Minions", "Climate Change", "B");
        Question questionList[] = {q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12}; 

        //System.out.println("\n Test done with question list based constructor");
        quiz = new Quiz(questionList);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        textLabel = new javax.swing.JLabel();
        prosButton = new javax.swing.JButton();
        consButton = new javax.swing.JButton();
        initiativesButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        optionA = new javax.swing.JRadioButton();
        optionB = new javax.swing.JRadioButton();
        optionC = new javax.swing.JRadioButton();
        optionD = new javax.swing.JRadioButton();
        answerButton = new javax.swing.JButton();
        questionLabel = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        answerLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        learnButton = new javax.swing.JButton();
        quizButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));

        textLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/environmental/stewardship/assignment/personal_computer.jpg"))); // NOI18N
        textLabel.setText("<html>Technology as an idea and a concept is intrinsically neutral in its impacts on human society and the environment.<br>The way it is used creates both the good and bad of technology, so it is hard to label it as either. <br>Click on the following pages to learn more about the good, bad and other interesting and useful <br>information about technology and its impacts on you.<br>Environmental Stewardship is the practice of actively participating in and being aware of environmental conservation efforts and sustainable practices of using technology to ensure the health and safety of the earth and human society. <br>Use this application to familiarize yourself with Environmental Stewardship");
        textLabel.setPreferredSize(new java.awt.Dimension(600, 600));

        prosButton.setText("Pros");
        prosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosButtonActionPerformed(evt);
            }
        });

        consButton.setText("Cons");
        consButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consButtonActionPerformed(evt);
            }
        });

        initiativesButton.setText("Initiatives&Involvement");
        initiativesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initiativesButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.setToolTipText("");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(prosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(initiativesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(textLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosButton)
                    .addComponent(consButton)
                    .addComponent(initiativesButton)
                    .addComponent(backButton))
                .addGap(36, 36, 36))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 400));

        optionA.setText("A");
        optionA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionA.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        optionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionAActionPerformed(evt);
            }
        });

        optionB.setText("B");
        optionB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        optionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBActionPerformed(evt);
            }
        });

        optionC.setText("C");
        optionC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        optionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionCActionPerformed(evt);
            }
        });

        optionD.setText("D");
        optionD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        optionD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionDActionPerformed(evt);
            }
        });

        answerButton.setText("Submit");
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        questionLabel.setText("jLabel2");

        menuButton.setText("Main Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(menuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(answerButton)
                        .addGap(18, 18, 18)
                        .addComponent(answerLabel))
                    .addComponent(optionD)
                    .addComponent(optionC)
                    .addComponent(optionA)
                    .addComponent(optionB)
                    .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(questionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(answerButton)
                    .addComponent(answerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuButton)
                    .addComponent(resultLabel))
                .addContainerGap(731, Short.MAX_VALUE))
        );

        jPanel1.setRequestFocusEnabled(false);

        learnButton.setText("Learn");
        learnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learnButtonActionPerformed(evt);
            }
        });

        quizButton.setText("Start Quiz");
        quizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizButtonActionPerformed(evt);
            }
        });

        quitButton.setText("QUIT");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(learnButton)
                        .addGap(452, 452, 452))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(quizButton)
                        .addGap(441, 441, 441))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(quitButton)
                        .addGap(451, 451, 451))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(learnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitButton)
                .addContainerGap(644, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void quizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizButtonActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        jPanel1.setVisible(false);
        questionNum = 0;
        answerLabel.setText("");
        resultLabel.setText("");
        quiz.askQuestion(questionNum,questionLabel,optionA,optionB,optionC,optionD);
    }//GEN-LAST:event_quizButtonActionPerformed

    private void learnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learnButtonActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_learnButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
        textLabel.setText("<html>Technology as an idea and a concept is intrinsically neutral in its impacts on human society and the environment.<br>The way it is used creates both the good and bad of technology, so it is hard to label it as either. <br>Click on the following pages to learn more about the good, bad and other interesting and useful <br>information about technology and its impacts on you.<br>Environmental Stewardship is the practice of actively participating in and being aware of environmental conservation efforts and sustainable practices of using technology to ensure the health and safety of the earth and human society. <br>Use this application to familiarize yourself with Environmental Stewardship");
        textLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/environmental/stewardship/assignment/personal_computer.jpg")));
    }//GEN-LAST:event_backButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
        
        optionA.setSelected(false);
        optionB.setSelected(false);
        optionC.setSelected(false);
        optionD.setSelected(false);
        resetQuiz();
        
        
    }//GEN-LAST:event_menuButtonActionPerformed

    private void initiativesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initiativesButtonActionPerformed
        // TODO add your handling code here:
        textLabel.setText("<html>Initiatives To Support and Use:<br> Electronic Products Recycling Association Ontario:<br>" +
"EPRA is an initiative that I like because it's a dedicated e-waste pickup company. It offers a low cost - free service that allows both people and companies to easily dispose of their electronics that they no longer need. The company is dedicated to creating a safe way for people to dispose of e-waste in all the steps of the process. They ensure that every person and worker and the environment is protected from harm in the recycling process, and they actively collect and reuse commonly used electronics materials such as glass, gold, silver, aluminum and copper to reduce the impacts of mining for these materials.Their free to no cost service incentivizes people and companies to reduce e-waste as through services like EPRA it no longer costs a lot to recycle e-waste efficiency. <br>" +
"<html><br>" +
"<html>CNA - Canadian Nuclear Association:<br>" +
"<html>The CNA is another initiative that I like because its a company that actively researches technologies like nuclear energy that can help reduce the negative environmental impact of technology on the environment. Nuclear energy currently is one of the cleanest sources of energy production per square unit of area. So companies that help further the research and development of nuclear technologies can actively help fight pollution, greenhouse gasses  and global warming. The CNA also uses their expertise on nuclear technologies to diagnose and treat many illnesses and also provides sterilization services, which helps the medical industry.<br>");
        textLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/environmental/stewardship/assignment/cna-logo-en.png")));
    }//GEN-LAST:event_initiativesButtonActionPerformed

    private void consButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consButtonActionPerformed
        // TODO add your handling code here:
        textLabel.setText("<html>Cons:	<br>The rapid industrialization of the world from which created the advanced technology that lets humans have the quality of life we have right now, is also the leading cause of global warming, and is actively destroying the planet causing major issues for humanity and the planet in the long term. E-Waste from technology is also not managed properly by civilians nor corporations on many accounts. <br>" +
"	<html>Since electronic parts are made up of several different materials and components, often times too small or intricately made to be separated and disposed easily, so many people often dispose of them incorrectly leading to entire landfills of e-waste to be formed or disposed and shipped off to developing countries often destroying their landscapes and environment.<br>" +
"	<html>The creation of modern technologies also requires lots of energy in the creation process and adds to the greenhouse effect, while also simultaneously draining the earth’s rare metal resources and causing pollution and destruction of wildlife and habitats in the mining process, since e-waste isn’t recycled well enough to slow down this process.<br>" +
"	<html>On a smaller scale Technology such as personal computers and phones has also rapidly changed the way society works and also how humans behave. The existence of social media allows for easier forms of bullying and harassment and also provides a stage for radicalized extremists to commune. The personalization of technology has also lead to negative physiological impacts to many people as well, by increasing the amount of people who end up with bad posture due to poor ergonomics in their use of technology, as well as people who end up with disturbed or broken sleep schedules due to the bright blue lights in phones messing with human circadian rhythms and preventing proper sleep.");
        textLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/environmental/stewardship/assignment/eWaste.jpg")));
    }//GEN-LAST:event_consButtonActionPerformed

    private void prosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosButtonActionPerformed
        // TODO add your handling code here:
        textLabel.setText("<html>Pros:<br> The rise of technology led to the invention of many major health related devices such as insulin pumps, centrifuges, RNA printers(Which were used to produce Covid MRNA vaccines) etc. all of which have played a major role in curing and significantly reducing the impact of diseases on humanity. <br>" +
"<html>Technology also plays a crucial role in providing the significantly higher life expectancy that humans experience right now, which is all thanks to technological systems that helped the medical and many other industries like sanitation, waste management, food production, ventilation and temperature control, transportation, information technology etc.<br>" +
"<html>Especially in the field of information technology, technology has vastly revolutionized how communications, information and trade works in the world, allowing for humans to spread out further and inhabit and live anywhere in the world as easy access to rapid communication and information technology helps to relieve the dangers of the unknown as well as keeping people connected which takes care of sociological aspects of human health when far away.<br>" +
"<html>Even when not taking the quality of life improvements brought to humanity by technology, it still has many benefits, modern technology is being researched, studied and created to counteract the climate change brought on by the industrialization of the world that gave humans this upgrade to quality of life.<br>" +
"<html>Technology has allowed humans to tap into the energy of the atom which allows us to cleanly create energy, and current researchers are aiming to eventually develop technologies that allow humans to imitate the energy production of the sun through nuclear fusion that will allow us to simultaneously improve quality of life and counteract climate change.");
        textLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/environmental/stewardship/assignment/medical_tech.jpg")));
    }//GEN-LAST:event_prosButtonActionPerformed

    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        // TODO add your handling code here:
        optionA.setSelected(false);
        optionB.setSelected(false);
        optionC.setSelected(false);
        optionD.setSelected(false);
        System.out.println(answerSelected);
        if (answerSelected.equals("x")){
            answerLabel.setText("Please Select an Option");
        }else{
            try{
                if(quiz.answer(questionNum,answerSelected)){
                   answerLabel.setText("CORRECT"); 
                }else{
                   answerLabel.setText("WRONG");
                }
                questionNum+=1;
                quiz.askQuestion(questionNum,questionLabel,optionA,optionB,optionC,optionD);
                resultLabel.setText("Score: "+quiz.getResults());
                if(questionNum>=quiz.getQuizLength()){
                    questionLabel.setText("COMPLETE: Return to Menu and come Back to Retry");
                    optionA.setText("");
                    optionB.setText("");
                    optionC.setText("");
                    optionD.setText("");
                    
                }
                
            }catch(Exception e){
                answerLabel.setText("<html>Completed<br> leave and come back to retry ");
                resultLabel.setText("Score: "+quiz.getResults());
            }
        }
        answerSelected = "x";
    }//GEN-LAST:event_answerButtonActionPerformed

    private void optionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionAActionPerformed
        // TODO add your handling code here:
        optionB.setSelected(false);
        optionC.setSelected(false);
        optionD.setSelected(false);
        answerSelected = "A";
    }//GEN-LAST:event_optionAActionPerformed

    private void optionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBActionPerformed
        // TODO add your handling code here:
        optionA.setSelected(false);
        optionC.setSelected(false);
        optionD.setSelected(false);
        answerSelected = "B";
    }//GEN-LAST:event_optionBActionPerformed

    private void optionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionCActionPerformed
        // TODO add your handling code here:
        optionB.setSelected(false);
        optionA.setSelected(false);
        optionD.setSelected(false);
        answerSelected = "C";
    }//GEN-LAST:event_optionCActionPerformed

    private void optionDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionDActionPerformed
        // TODO add your handling code here:
        optionB.setSelected(false);
        optionC.setSelected(false);
        optionA.setSelected(false);
        answerSelected = "D";
    }//GEN-LAST:event_optionDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gui.setVisible(true);
            }
        });
    }
    public static GUI gui = new GUI();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton consButton;
    private javax.swing.JButton initiativesButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton learnButton;
    private javax.swing.JButton menuButton;
    private javax.swing.JRadioButton optionA;
    private javax.swing.JRadioButton optionB;
    private javax.swing.JRadioButton optionC;
    private javax.swing.JRadioButton optionD;
    private javax.swing.JButton prosButton;
    public javax.swing.JLabel questionLabel;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton quizButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
    private String answerSelected = "x";
    private int questionNum = 0;
    private Quiz quiz;
}
